import { randomUUID } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { join } from 'node:path';

import { CloudApiClient } from './api-client';
import { BundleStore, assertValidBundleId } from './bundle-store';
import type {
  DeleteBundleOptions,
  DownloadBundleOptions,
  DownloadBundleProgressEvent,
  FetchChannelsOptions,
  FetchChannelsResult,
  FetchLatestBundleOptions,
  FetchLatestBundleResult,
  GetBlockedBundlesResult,
  GetChannelResult,
  GetCurrentBundleResult,
  GetCustomIdResult,
  GetDeviceIdResult,
  GetDownloadedBundlesResult,
  GetNextBundleResult,
  GetVersionCodeResult,
  GetVersionNameResult,
  IsSyncingResult,
  NextBundleSetEvent,
  ReadyResult,
  RolledBackEvent,
  SetChannelOptions,
  SetCustomIdOptions,
  SetNextBundleOptions,
  SyncOptions,
  SyncResult,
} from './definitions';
import { downloadFile } from './download';
import { ErrorCode, LiveUpdateError, unknownError } from './errors';
import { StateFile } from './state-file';
import {
  calculateContentChecksums,
  parsePublicKey,
  verifyContentChecksums,
  verifyDownloadedFile,
} from './verify';
import { extractZip, findIndexHtmlDirectory } from './zip';

/**
 * Logger used by the engine. Defaults to `console`.
 *
 * @since 0.1.0
 */
export interface LiveUpdateLogger {
  debug(message: string): void;
  error(message: string): void;
  info(message: string): void;
  warn(message: string): void;
}

/**
 * Configuration of the live update engine.
 *
 * The engine is host-agnostic: everything that depends on the runtime
 * (paths, version information, platform identity) is injected.
 *
 * @since 0.1.0
 */
export interface LiveUpdateEngineConfig {
  /**
   * The app ID is used to identify the app when using
   * [Capawesome Cloud](https://capawesome.io/cloud/).
   *
   * This is **NOT** the same as the app identifier (e.g. `com.example.app`).
   * This is a unique identifier generated by Capawesome Cloud
   * (e.g. `6e351b4f-69a7-415e-a057-4567df7ffe94`).
   *
   * Required for `sync()` and `fetchLatestBundle()`. Not required when
   * bundles are managed manually via `downloadBundle()`.
   *
   * @since 0.1.0
   * @example '6e351b4f-69a7-415e-a057-4567df7ffe94'
   */
  appId?: string;
  /**
   * Whether or not to automatically block bundles that have been rolled back.
   *
   * When enabled, the engine will automatically block bundles that caused
   * a rollback (up to 100 bundles). When the limit is reached, the oldest
   * blocked bundle is unblocked. Blocked bundles will be skipped in future
   * sync operations.
   *
   * **Attention**: This option has no effect if `readyTimeout` is set to `0`.
   *
   * @since 0.1.0
   * @default false
   */
  autoBlockRolledBackBundles?: boolean;
  /**
   * Whether or not to automatically delete unused bundles.
   *
   * When enabled, the engine will automatically delete unused bundles after
   * calling `ready()`. The current bundle, the next bundle and the last
   * bundle that successfully signaled readiness are never deleted.
   *
   * @since 0.1.0
   * @default false
   */
  autoDeleteBundles?: boolean;
  /**
   * The directory where the engine stores its bundles and state.
   *
   * The directory is created if it does not exist. It must be writable
   * and should be excluded from any file synchronization (e.g. backups).
   *
   * @since 0.1.0
   */
  dataDirectory: string;
  /**
   * The default channel of the app.
   *
   * This can be overridden by `setChannel()` or the `channel` parameter
   * of `sync()`.
   *
   * @since 0.1.0
   * @example 'production'
   */
  defaultChannel?: string;
  /**
   * The timeout in milliseconds for HTTP requests.
   *
   * @since 0.1.0
   * @default 60000
   */
  httpTimeout?: number;
  /**
   * A custom logger.
   *
   * @since 0.1.0
   * @default console
   */
  logger?: LiveUpdateLogger;
  /**
   * The operating system version reported to Capawesome Cloud.
   *
   * @since 0.1.0
   */
  osVersion: string;
  /**
   * The platform identifier reported to Capawesome Cloud.
   *
   * @since 0.1.0
   */
  platform: string;
  /**
   * The plugin version reported to Capawesome Cloud (the `pluginVersion`
   * request parameter).
   *
   * Defaults to `sdkVersion`. The standalone Electron SDK reports the
   * engine version; a Capacitor adapter reports the plugin package
   * version.
   *
   * @since 0.1.0
   */
  pluginVersion?: string;
  /**
   * The public key to verify the integrity of the bundle.
   *
   * The public key must be a PEM-encoded RSA public key.
   *
   * @since 0.1.0
   */
  publicKey?: string;
  /**
   * The timeout in milliseconds to wait for the app to be ready
   * before rolling back to the previous bundle.
   *
   * It is strongly **recommended** to configure this option (e.g. `10000` ms)
   * so that the SDK can roll back in case of problems: if configured, the
   * app must call `ready()` within this timeout after every start or reload
   * of a live update bundle. This also enables the kill-safe boot rollback:
   * a marker is persisted before a new bundle loads and is only cleared by
   * `ready()`, so a crash or kill during boot is detected on the next start.
   *
   * Set to `0` to disable rollback protection.
   *
   * @since 0.1.0
   * @default 0
   * @example 10000
   */
  readyTimeout?: number;
  /**
   * The runtime identifier reported to Capawesome Cloud.
   *
   * If not set, no runtime is reported and the server assumes its
   * default runtime.
   *
   * @since 0.1.0
   * @example 'electron'
   */
  runtime?: string;
  /**
   * The version of the SDK reported to Capawesome Cloud.
   *
   * @since 0.1.0
   */
  sdkVersion: string;
  /**
   * The API domain of the [Capawesome Cloud](https://cloud.capawesome.io)
   * server **without** scheme or path.
   *
   * @since 0.1.0
   * @default 'api.cloud.capawesome.io'
   * @example 'api.cloud.capawesome.eu'
   */
  serverDomain?: string;
  /**
   * The version code of the app reported to Capawesome Cloud.
   *
   * @since 0.1.0
   * @example '1'
   */
  versionCode: string;
  /**
   * The version name of the app reported to Capawesome Cloud.
   *
   * @since 0.1.0
   * @example '1.0.0'
   */
  versionName: string;
}

/**
 * Result of `LiveUpdateEngine.initialize()`.
 *
 * @since 0.1.0
 */
export interface InitializeResult {
  /**
   * The unique identifier of the bundle that should be loaded.
   *
   * If `null`, the default bundle should be loaded.
   *
   * @since 0.1.0
   */
  currentBundleId: string | null;
  /**
   * Whether the engine rolled back to a previous bundle because the
   * last boot died before the app signaled readiness.
   *
   * @since 0.1.0
   */
  rollback: boolean;
}

/**
 * Result of `LiveUpdateEngine.applyNextBundle()`.
 *
 * @since 0.1.0
 */
export interface ApplyNextBundleResult {
  /**
   * The unique identifier of the bundle that should be loaded now.
   *
   * If `null`, the default bundle should be loaded.
   *
   * @since 0.1.0
   */
  currentBundleId: string | null;
}

export interface EngineEventMap {
  downloadBundleProgress: DownloadBundleProgressEvent;
  nextBundleSet: NextBundleSetEvent;
  rolledBack: RolledBackEvent;
}

const DEFAULT_HTTP_TIMEOUT = 60000;
const DEFAULT_READY_TIMEOUT = 0;
const DEFAULT_SERVER_DOMAIN = 'api.cloud.capawesome.io';
const MAX_BLOCKED_BUNDLES = 100;
const DEFAULT_FETCH_CHANNELS_LIMIT = 50;
const DEFAULT_FETCH_CHANNELS_OFFSET = 0;

const defaultLogger: LiveUpdateLogger = {
  debug: message => console.debug(`[LiveUpdate] ${message}`),
  error: message => console.error(`[LiveUpdate] ${message}`),
  info: message => console.info(`[LiveUpdate] ${message}`),
  warn: message => console.warn(`[LiveUpdate] ${message}`),
};

/**
 * The live update engine.
 *
 * Pure Node.js update logic: Cloud protocol client, bundle store,
 * persisted state with a kill-safe rollback state machine, and the
 * download/extract/verify pipeline. The engine has no dependency on
 * Electron or Capacitor; hosts inject paths and platform identity.
 *
 * Lifecycle: construct, `await initialize()` once at process start
 * (BEFORE loading any web content), then use the vocabulary methods.
 *
 * @since 0.1.0
 */
export class LiveUpdateEngine {
  private readonly apiClient: CloudApiClient;
  private readonly appId: string | null;
  private readonly autoBlockRolledBackBundles: boolean;
  private readonly autoDeleteBundles: boolean;
  private readonly defaultChannel: string | null;
  private readonly emitter = new EventEmitter();
  private readonly httpTimeout: number;
  private initialized = false;
  private readonly logger: LiveUpdateLogger;
  private readonly osVersion: string;
  private readonly platform: string;
  private readonly pluginVersion: string;
  private readonly publicKey: string | undefined;
  private readonly readyTimeout: number;
  private rollbackPerformed = false;
  private readonly runtime: string | null;
  private readonly sdkVersion: string;
  private readonly stateFile: StateFile;
  private readonly store: BundleStore;
  private syncInProgress = false;
  private readonly versionCode: string;
  private readonly versionName: string;
  private watchdogTimer: NodeJS.Timeout | null = null;

  constructor(config: LiveUpdateEngineConfig) {
    this.appId = config.appId ?? null;
    this.autoBlockRolledBackBundles =
      config.autoBlockRolledBackBundles ?? false;
    this.autoDeleteBundles = config.autoDeleteBundles ?? false;
    this.defaultChannel = config.defaultChannel ?? null;
    this.httpTimeout = config.httpTimeout ?? DEFAULT_HTTP_TIMEOUT;
    this.logger = config.logger ?? defaultLogger;
    this.osVersion = config.osVersion;
    this.platform = config.platform;
    this.pluginVersion = config.pluginVersion ?? config.sdkVersion;
    this.publicKey = config.publicKey;
    this.readyTimeout = config.readyTimeout ?? DEFAULT_READY_TIMEOUT;
    this.runtime = config.runtime ?? null;
    this.sdkVersion = config.sdkVersion;
    this.versionCode = config.versionCode;
    this.versionName = config.versionName;
    this.apiClient = new CloudApiClient({
      httpTimeout: this.httpTimeout,
      serverDomain: config.serverDomain ?? DEFAULT_SERVER_DOMAIN,
    });
    this.stateFile = new StateFile(config.dataDirectory);
    this.store = new BundleStore(config.dataDirectory);
    if (this.publicKey) {
      // Fail fast on a malformed key instead of at the first download.
      parsePublicKey(this.publicKey);
    }
  }

  /**
   * Initialize the engine.
   *
   * Must be called once at process start, BEFORE any web content is
   * loaded. This is where the kill-safe rollback happens: if the
   * previous boot wrote a pending-boot marker that was never cleared
   * by `ready()`, the engine reverts to the last bundle that
   * successfully signaled readiness (or the default bundle) and
   * blocks the failed bundle if `autoBlockRolledBackBundles` is
   * enabled. Afterwards, a pending next bundle is promoted to the
   * current bundle and, if rollback protection is active, a new
   * pending-boot marker is persisted before this method resolves.
   *
   * @since 0.1.0
   */
  public async initialize(): Promise<InitializeResult> {
    await this.stateFile.load();
    await this.store.initialize();
    await this.reconcileBundleMetadata();
    const state = this.stateFile.get();
    const marker = state.pendingBoot;
    const originalNext = state.nextBundleId;
    if (marker) {
      // The previous boot loaded a bundle and died before ready().
      const failedBundleId = marker.bundleId;
      this.logger.warn(
        `The app was not ready within the last boot of bundle '${failedBundleId}'. Rolling back.`,
      );
      // A pending next bundle different from the failed one wins over
      // the fallback: it may be the fix that was synced in the background.
      const preferred =
        originalNext !== null && originalNext !== failedBundleId
          ? originalNext
          : undefined;
      const target = await this.resolveUsableBundle(
        preferred === undefined
          ? [state.lastSuccessfulBundleId]
          : [preferred, state.lastSuccessfulBundleId],
      );
      await this.stateFile.update(s => {
        s.previousBundleId = failedBundleId;
        s.currentBundleId = target;
        s.nextBundleId = target;
        s.pendingBoot = null;
        if (this.autoBlockRolledBackBundles) {
          this.blockBundleIdInState(s, failedBundleId);
        }
      });
      this.rollbackPerformed = true;
    } else if (originalNext !== state.currentBundleId) {
      // Promote the pending next bundle (set by sync()/setNextBundle()
      // before the last shutdown) with activation-time re-verification.
      let target = state.currentBundleId;
      if (originalNext === null) {
        target = null;
      } else if (await this.verifyBundleForActivation(originalNext)) {
        target = originalNext;
      } else {
        this.logger.error(
          `Bundle '${originalNext}' failed activation verification and was discarded.`,
        );
      }
      await this.stateFile.update(s => {
        s.currentBundleId = target;
        s.nextBundleId = target;
      });
    }
    // The current bundle may have been deleted or corrupted externally.
    const currentBundleId = this.stateFile.get().currentBundleId;
    if (currentBundleId !== null && !(await this.store.has(currentBundleId))) {
      this.logger.warn(`Bundle '${currentBundleId}' is missing. Falling back.`);
      const target = await this.resolveUsableBundle([
        this.stateFile.get().lastSuccessfulBundleId,
      ]);
      await this.stateFile.update(s => {
        s.currentBundleId = target;
        s.nextBundleId = target;
      });
    }
    this.initialized = true;
    await this.armRollbackProtection();
    return {
      currentBundleId: this.stateFile.get().currentBundleId,
      rollback: this.rollbackPerformed,
    };
  }

  /**
   * Promote the next bundle to the current bundle without restarting
   * the process. Called by hosts when the app is reloaded.
   *
   * Re-verifies the bundle content against the checksums recorded at
   * install time before activating it, and re-arms rollback protection.
   *
   * @since 0.1.0
   */
  public async applyNextBundle(): Promise<ApplyNextBundleResult> {
    this.assertInitialized();
    this.stopWatchdog();
    const state = this.stateFile.get();
    const next = state.nextBundleId;
    if (next !== state.currentBundleId) {
      if (next !== null && !(await this.verifyBundleForActivation(next))) {
        await this.stateFile.update(s => {
          s.nextBundleId = s.currentBundleId;
        });
        throw new LiveUpdateError(
          ErrorCode.ChecksumMismatch,
          'Checksum mismatch.',
        );
      }
      await this.stateFile.update(s => {
        s.currentBundleId = next;
      });
    }
    await this.armRollbackProtection();
    return { currentBundleId: this.stateFile.get().currentBundleId };
  }

  /**
   * Notify the engine that the app is ready to use and no rollback is
   * needed. Clears the pending-boot marker and stops the watchdog.
   *
   * @since 0.1.0
   */
  public async ready(): Promise<ReadyResult> {
    this.assertInitialized();
    this.stopWatchdog();
    if (this.readyTimeout <= 0) {
      this.logger.warn(
        'readyTimeout is not configured. It is strongly recommended to configure it (e.g. 10000 ms) so that the SDK can roll back in case of problems.',
      );
    }
    const state = this.stateFile.get();
    const result: ReadyResult = {
      currentBundleId: state.currentBundleId,
      previousBundleId: state.previousBundleId,
      rollback: this.rollbackPerformed,
    };
    await this.stateFile.update(s => {
      s.pendingBoot = null;
      if (s.currentBundleId !== null) {
        s.lastSuccessfulBundleId = s.currentBundleId;
      }
      s.previousBundleId = s.currentBundleId;
    });
    this.rollbackPerformed = false;
    if (this.autoDeleteBundles) {
      await this.deleteUnusedBundles();
    }
    return result;
  }

  /**
   * Automatically download and set the latest bundle for the app using
   * the [Capawesome Cloud](https://capawesome.io/cloud/).
   *
   * @since 0.1.0
   */
  public async sync(options?: SyncOptions): Promise<SyncResult> {
    this.assertInitialized();
    if (this.syncInProgress) {
      throw new LiveUpdateError(
        ErrorCode.SyncInProgress,
        'Sync is already in progress.',
      );
    }
    this.syncInProgress = true;
    try {
      const latest = await this.fetchLatestBundleInternal(options?.channel);
      if (!latest) {
        this.logger.info('No update available.');
        return { nextBundleId: null };
      }
      const bundleId = latest.bundleId;
      const state = this.stateFile.get();
      if (state.blockedBundleIds.includes(bundleId)) {
        this.logger.info(
          `Bundle '${bundleId}' is blocked and will be skipped.`,
        );
        return { nextBundleId: null };
      }
      if (bundleId === state.currentBundleId) {
        return { nextBundleId: null };
      }
      if (!(await this.store.has(bundleId))) {
        if (latest.artifactType === 'manifest') {
          throw new LiveUpdateError(
            ErrorCode.ArtifactTypeNotSupported,
            'The manifest artifact type is not yet supported by this SDK.',
          );
        }
        await this.downloadBundleInternal({
          bundleId,
          checksum: latest.checksum,
          signature: latest.signature,
          url: latest.url,
        });
      }
      await this.setNextBundleInternal(bundleId);
      return { nextBundleId: bundleId };
    } finally {
      this.syncInProgress = false;
    }
  }

  /**
   * Fetch the latest bundle using the [Capawesome Cloud](https://capawesome.io/cloud/).
   *
   * @since 0.1.0
   */
  public async fetchLatestBundle(
    options?: FetchLatestBundleOptions,
  ): Promise<FetchLatestBundleResult> {
    this.assertInitialized();
    const latest = await this.fetchLatestBundleInternal(options?.channel);
    if (!latest) {
      return { bundleId: null };
    }
    return {
      artifactType: latest.artifactType,
      bundleId: latest.bundleId,
      channel: latest.channelName,
      checksum: latest.checksum,
      customProperties: latest.customProperties,
      downloadUrl: latest.url,
      signature: latest.signature,
    };
  }

  /**
   * Fetch the available channels using the [Capawesome Cloud](https://capawesome.io/cloud/).
   *
   * Only works for apps with public channels enabled (Channel
   * Discovery). Throws `ChannelDiscoveryNotEnabled` otherwise.
   *
   * @since 0.1.0
   */
  public async fetchChannels(
    options?: FetchChannelsOptions,
  ): Promise<FetchChannelsResult> {
    this.assertInitialized();
    if (!this.appId) {
      throw new LiveUpdateError(
        ErrorCode.AppIdMissing,
        'appId must be configured.',
      );
    }
    const channels = await this.apiClient.getChannels({
      appId: this.appId,
      deviceId: await this.getOrCreateDeviceId(),
      limit: options?.limit ?? DEFAULT_FETCH_CHANNELS_LIMIT,
      offset: options?.offset ?? DEFAULT_FETCH_CHANNELS_OFFSET,
      query: options?.query ?? null,
    });
    return { channels };
  }

  /**
   * Download a bundle.
   *
   * The download is verified (signature or checksum), extracted with
   * zip-slip protection and installed atomically.
   *
   * @since 0.1.0
   */
  public async downloadBundle(options: DownloadBundleOptions): Promise<void> {
    this.assertInitialized();
    if (!options.url) {
      throw new LiveUpdateError(ErrorCode.UrlMissing, 'url must be provided.');
    }
    assertValidBundleId(options.bundleId);
    if (options.artifactType === 'manifest') {
      throw new LiveUpdateError(
        ErrorCode.ArtifactTypeNotSupported,
        'The manifest artifact type is not yet supported by this SDK.',
      );
    }
    if (await this.store.has(options.bundleId)) {
      throw new LiveUpdateError(
        ErrorCode.BundleAlreadyExists,
        'bundle already exists.',
      );
    }
    await this.downloadBundleInternal({
      bundleId: options.bundleId,
      checksum: options.checksum,
      signature: options.signature,
      url: options.url,
    });
  }

  /**
   * Delete a bundle from the app.
   *
   * @since 0.1.0
   */
  public async deleteBundle(options: DeleteBundleOptions): Promise<void> {
    this.assertInitialized();
    if (!options.bundleId) {
      throw new LiveUpdateError(
        ErrorCode.BundleIdMissing,
        'bundleId must be provided.',
      );
    }
    await this.store.delete(options.bundleId);
    await this.stateFile.update(s => {
      delete s.bundles[options.bundleId];
      if (s.nextBundleId === options.bundleId) {
        s.nextBundleId =
          s.currentBundleId === options.bundleId ? null : s.currentBundleId;
      }
      if (s.lastSuccessfulBundleId === options.bundleId) {
        s.lastSuccessfulBundleId = null;
      }
    });
  }

  /**
   * Set the next bundle to use for the app.
   *
   * @since 0.1.0
   */
  public async setNextBundle(options: SetNextBundleOptions): Promise<void> {
    this.assertInitialized();
    if (options.bundleId === null) {
      await this.setNextBundleInternal(null);
      return;
    }
    if (!options.bundleId) {
      throw new LiveUpdateError(
        ErrorCode.BundleIdMissing,
        'bundleId must be provided.',
      );
    }
    if (!(await this.store.has(options.bundleId))) {
      throw new LiveUpdateError(ErrorCode.BundleNotFound, 'bundle not found.');
    }
    await this.setNextBundleInternal(options.bundleId);
  }

  /**
   * Reset the app to the default bundle.
   *
   * @since 0.1.0
   */
  public async reset(): Promise<void> {
    this.assertInitialized();
    await this.setNextBundleInternal(null);
  }

  /**
   * Get the bundle identifier of the current bundle.
   *
   * @since 0.1.0
   */
  public async getCurrentBundle(): Promise<GetCurrentBundleResult> {
    this.assertInitialized();
    return { bundleId: this.stateFile.get().currentBundleId };
  }

  /**
   * Get the absolute path of the current bundle on disk.
   *
   * If `null`, the default bundle is being used.
   *
   * @since 0.1.0
   */
  public getCurrentBundlePath(): string | null {
    this.assertInitialized();
    const currentBundleId = this.stateFile.get().currentBundleId;
    return currentBundleId === null
      ? null
      : this.store.getPath(currentBundleId);
  }

  /**
   * Get the bundle identifier of the next bundle.
   *
   * @since 0.1.0
   */
  public async getNextBundle(): Promise<GetNextBundleResult> {
    this.assertInitialized();
    return { bundleId: this.stateFile.get().nextBundleId };
  }

  /**
   * Get all identifiers of bundles that have been downloaded.
   *
   * @since 0.1.0
   */
  public async getDownloadedBundles(): Promise<GetDownloadedBundlesResult> {
    this.assertInitialized();
    return { bundleIds: await this.store.list() };
  }

  /**
   * Get all blocked bundle identifiers.
   *
   * @since 0.1.0
   */
  public async getBlockedBundles(): Promise<GetBlockedBundlesResult> {
    this.assertInitialized();
    return { bundleIds: [...this.stateFile.get().blockedBundleIds] };
  }

  /**
   * Clear all blocked bundles from the blocked list.
   *
   * @since 0.1.0
   */
  public async clearBlockedBundles(): Promise<void> {
    this.assertInitialized();
    await this.stateFile.update(s => {
      s.blockedBundleIds = [];
    });
  }

  /**
   * Get the channel that is used for the update.
   *
   * @since 0.1.0
   */
  public async getChannel(): Promise<GetChannelResult> {
    this.assertInitialized();
    return { channel: this.stateFile.get().channel ?? this.defaultChannel };
  }

  /**
   * Set the channel to use for the update.
   *
   * @since 0.1.0
   */
  public async setChannel(options: SetChannelOptions): Promise<void> {
    this.assertInitialized();
    await this.stateFile.update(s => {
      s.channel = options.channel;
    });
  }

  /**
   * Get the custom identifier of the device.
   *
   * @since 0.1.0
   */
  public async getCustomId(): Promise<GetCustomIdResult> {
    this.assertInitialized();
    return { customId: this.stateFile.get().customId };
  }

  /**
   * Set the custom identifier of the device.
   *
   * @since 0.1.0
   */
  public async setCustomId(options: SetCustomIdOptions): Promise<void> {
    this.assertInitialized();
    await this.stateFile.update(s => {
      s.customId = options.customId;
    });
  }

  /**
   * Get the unique device identifier.
   *
   * The identifier is a random UUID that is generated on first use and
   * persisted per app ID.
   *
   * @since 0.1.0
   */
  public async getDeviceId(): Promise<GetDeviceIdResult> {
    this.assertInitialized();
    return { deviceId: await this.getOrCreateDeviceId() };
  }

  /**
   * Get the version code of the app.
   *
   * @since 0.1.0
   */
  public async getVersionCode(): Promise<GetVersionCodeResult> {
    this.assertInitialized();
    return { versionCode: this.versionCode };
  }

  /**
   * Get the version name of the app.
   *
   * @since 0.1.0
   */
  public async getVersionName(): Promise<GetVersionNameResult> {
    this.assertInitialized();
    return { versionName: this.versionName };
  }

  /**
   * Check whether a sync operation is currently in progress.
   *
   * @since 0.1.0
   */
  public async isSyncing(): Promise<IsSyncingResult> {
    this.assertInitialized();
    return { syncing: this.syncInProgress };
  }

  /**
   * Stop timers. The engine must not be used afterwards.
   *
   * @since 0.1.0
   */
  public destroy(): void {
    this.stopWatchdog();
    this.emitter.removeAllListeners();
  }

  /**
   * Listen for an engine event.
   *
   * @since 0.1.0
   */
  public on<T extends keyof EngineEventMap>(
    eventName: T,
    listener: (event: EngineEventMap[T]) => void,
  ): void {
    this.emitter.on(eventName, listener);
  }

  /**
   * Remove an engine event listener.
   *
   * @since 0.1.0
   */
  public off<T extends keyof EngineEventMap>(
    eventName: T,
    listener: (event: EngineEventMap[T]) => void,
  ): void {
    this.emitter.off(eventName, listener);
  }

  private emit<T extends keyof EngineEventMap>(
    eventName: T,
    event: EngineEventMap[T],
  ): void {
    this.emitter.emit(eventName, event);
  }

  private assertInitialized(): void {
    if (!this.initialized) {
      throw new LiveUpdateError(
        ErrorCode.NotInitialized,
        'The engine has not been initialized. Call initialize() first.',
      );
    }
  }

  private async fetchLatestBundleInternal(channelOverride?: string): Promise<{
    artifactType: 'manifest' | 'zip';
    bundleId: string;
    channelName?: string;
    checksum?: string;
    customProperties?: { [key: string]: string };
    signature?: string;
    url: string;
  } | null> {
    if (!this.appId) {
      throw new LiveUpdateError(
        ErrorCode.AppIdMissing,
        'appId must be configured.',
      );
    }
    const state = this.stateFile.get();
    const channel = channelOverride ?? state.channel ?? this.defaultChannel;
    return this.apiClient.getLatestBundle({
      appId: this.appId,
      appVersionCode: this.versionCode,
      appVersionName: this.versionName,
      bundleId: state.currentBundleId,
      channelName: channel,
      customId: state.customId,
      deviceId: await this.getOrCreateDeviceId(),
      osVersion: this.osVersion,
      platform: this.platform,
      pluginVersion: this.pluginVersion,
      runtime: this.runtime,
    });
  }

  private async downloadBundleInternal(options: {
    bundleId: string;
    checksum?: string;
    signature?: string;
    url: string;
  }): Promise<void> {
    const stagingDirectory = await this.store.createStagingDirectory();
    try {
      const zipFilePath = join(stagingDirectory, 'bundle.zip');
      const extractDirectory = join(stagingDirectory, 'extracted');
      const downloadResult = await downloadFile({
        destinationPath: zipFilePath,
        httpTimeout: this.httpTimeout,
        onProgress: (downloadedBytes, totalBytes) => {
          this.emit('downloadBundleProgress', {
            bundleId: options.bundleId,
            downloadedBytes,
            progress: totalBytes > 0 ? downloadedBytes / totalBytes : 0,
            totalBytes,
          });
        },
        url: options.url,
      });
      await verifyDownloadedFile({
        checksum: options.checksum ?? downloadResult.checksum,
        filePath: zipFilePath,
        publicKey: this.publicKey,
        signature: options.signature ?? downloadResult.signature,
      });
      await extractZip(zipFilePath, extractDirectory);
      const bundleRoot = await findIndexHtmlDirectory(extractDirectory);
      if (!bundleRoot) {
        throw new LiveUpdateError(
          ErrorCode.BundleIndexHtmlMissing,
          'The bundle does not contain an index.html file.',
        );
      }
      const fileChecksums = await calculateContentChecksums(bundleRoot);
      await this.store.add(options.bundleId, bundleRoot);
      await this.stateFile.update(s => {
        s.bundles[options.bundleId] = {
          fileChecksums,
          signed: this.publicKey !== undefined,
        };
      });
    } catch (error) {
      throw unknownError(error);
    } finally {
      await this.store.cleanUpStaging(stagingDirectory);
    }
  }

  private async setNextBundleInternal(bundleId: string | null): Promise<void> {
    await this.stateFile.update(s => {
      s.nextBundleId = bundleId;
    });
    this.emit('nextBundleSet', { bundleId });
  }

  private async getOrCreateDeviceId(): Promise<string> {
    const key = this.appId ?? '';
    const existing = this.stateFile.get().deviceIds[key];
    if (existing) {
      return existing;
    }
    const deviceId = randomUUID().toLowerCase();
    await this.stateFile.update(s => {
      s.deviceIds[key] = deviceId;
    });
    return deviceId;
  }

  private blockBundleIdInState(
    state: { blockedBundleIds: string[] },
    bundleId: string,
  ): void {
    if (state.blockedBundleIds.includes(bundleId)) {
      return;
    }
    state.blockedBundleIds.push(bundleId);
    while (state.blockedBundleIds.length > MAX_BLOCKED_BUNDLES) {
      state.blockedBundleIds.shift();
    }
  }

  /**
   * Verify that an installed bundle still matches the checksums that
   * were recorded when it was installed from the verified download.
   */
  private async verifyBundleForActivation(bundleId: string): Promise<boolean> {
    if (!(await this.store.has(bundleId))) {
      return false;
    }
    const metadata = this.stateFile.get().bundles[bundleId];
    if (!metadata) {
      // Bundle without metadata (e.g. placed on disk manually): there
      // is nothing to verify against.
      this.logger.warn(
        `No install-time checksums found for bundle '${bundleId}'.`,
      );
      return true;
    }
    const valid = await verifyContentChecksums(
      this.store.getPath(bundleId),
      metadata.fileChecksums,
    );
    if (!valid) {
      try {
        await this.store.delete(bundleId);
      } catch {
        // Removal is best effort; the bundle is unusable either way.
      }
      await this.stateFile.update(s => {
        delete s.bundles[bundleId];
      });
    }
    return valid;
  }

  /**
   * Return the first usable bundle of the given candidates, falling
   * back to `null` (the default bundle). Candidates are verified
   * against their install-time checksums.
   */
  private async resolveUsableBundle(
    candidates: (string | null)[],
  ): Promise<string | null> {
    for (const candidate of candidates) {
      if (candidate === null) {
        continue;
      }
      if (await this.verifyBundleForActivation(candidate)) {
        return candidate;
      }
    }
    return null;
  }

  private async reconcileBundleMetadata(): Promise<void> {
    const bundleIds = new Set(await this.store.list());
    const state = this.stateFile.get();
    const staleMetadata = Object.keys(state.bundles).filter(
      bundleId => !bundleIds.has(bundleId),
    );
    if (staleMetadata.length > 0) {
      await this.stateFile.update(s => {
        for (const bundleId of staleMetadata) {
          delete s.bundles[bundleId];
        }
      });
    }
  }

  /**
   * Arm the kill-safe pending-boot marker and the in-process watchdog
   * for the current bundle. Called after boot and after every reload.
   */
  private async armRollbackProtection(): Promise<void> {
    if (this.readyTimeout <= 0) {
      return;
    }
    const state = this.stateFile.get();
    const currentBundleId = state.currentBundleId;
    if (currentBundleId === null) {
      return;
    }
    if (currentBundleId !== state.lastSuccessfulBundleId) {
      // Persist the marker BEFORE the bundle is loaded. If the process
      // dies before ready() clears it, the next start rolls back.
      const attempts =
        state.pendingBoot && state.pendingBoot.bundleId === currentBundleId
          ? state.pendingBoot.attempts + 1
          : 1;
      await this.stateFile.update(s => {
        s.pendingBoot = { attempts, bundleId: currentBundleId };
      });
    }
    this.startWatchdog();
  }

  private startWatchdog(): void {
    this.stopWatchdog();
    this.watchdogTimer = setTimeout(() => {
      void this.performWatchdogRollback().catch(error => {
        this.logger.error(
          `Rollback failed: ${error instanceof Error ? error.message : String(error)}`,
        );
      });
    }, this.readyTimeout);
    // The watchdog must never keep the process alive.
    this.watchdogTimer.unref();
  }

  private stopWatchdog(): void {
    if (this.watchdogTimer) {
      clearTimeout(this.watchdogTimer);
      this.watchdogTimer = null;
    }
  }

  private async performWatchdogRollback(): Promise<void> {
    const state = this.stateFile.get();
    const failedBundleId = state.currentBundleId;
    if (failedBundleId === null) {
      return;
    }
    this.logger.warn(
      `The app was not ready within ${this.readyTimeout} ms. Rolling back.`,
    );
    const target = await this.resolveUsableBundle([
      state.lastSuccessfulBundleId,
    ]);
    await this.stateFile.update(s => {
      s.previousBundleId = failedBundleId;
      s.currentBundleId = target;
      s.nextBundleId = target;
      s.pendingBoot = null;
      if (this.autoBlockRolledBackBundles) {
        this.blockBundleIdInState(s, failedBundleId);
      }
    });
    this.rollbackPerformed = true;
    this.emit('rolledBack', {
      currentBundleId: target,
      previousBundleId: failedBundleId,
    });
  }

  private async deleteUnusedBundles(): Promise<void> {
    const state = this.stateFile.get();
    const usedBundleIds = new Set(
      [
        state.currentBundleId,
        state.nextBundleId,
        state.lastSuccessfulBundleId,
      ].filter((bundleId): bundleId is string => bundleId !== null),
    );
    for (const bundleId of await this.store.list()) {
      if (!usedBundleIds.has(bundleId)) {
        try {
          await this.store.delete(bundleId);
          await this.stateFile.update(s => {
            delete s.bundles[bundleId];
          });
        } catch {
          this.logger.warn(`Failed to delete unused bundle '${bundleId}'.`);
        }
      }
    }
  }
}
