import type { BrowserWindow } from 'electron';

import type { LiveUpdateApi } from '../engine/definitions';
import type { LiveUpdateLogger } from '../engine/engine';

/**
 * The auto-update strategy for live updates.
 *
 * - `none`: Live updates will not be applied automatically.
 * - `background`: Live updates will be automatically downloaded and set
 *   as the next bundle in the background at app startup, when the app
 *   is focused and when the system resumes from sleep (if the last
 *   check was more than 15 minutes ago). The new bundle is applied on
 *   the next app restart or `reload()` call.
 *
 * @since 0.1.0
 */
export type AutoUpdateStrategy = 'background' | 'none';

/**
 * Configuration of the live update SDK.
 *
 * @since 0.1.0
 */
export interface LiveUpdateConfig {
  /**
   * The app ID is used to identify the app when using
   * [Capawesome Cloud](https://capawesome.io/cloud/).
   *
   * This is **NOT** the same as the app identifier (e.g. `com.example.app`).
   * This is a unique identifier generated by Capawesome Cloud
   * (e.g. `6e351b4f-69a7-415e-a057-4567df7ffe94`).
   *
   * Required for `sync()` and `fetchLatestBundle()`. Not required when
   * bundles are managed manually via `downloadBundle()`.
   *
   * @since 0.1.0
   * @example '6e351b4f-69a7-415e-a057-4567df7ffe94'
   */
  appId?: string;
  /**
   * Whether or not to automatically block bundles that have been rolled back.
   *
   * When enabled, the SDK will automatically block bundles that caused
   * a rollback (up to 100 bundles). When the limit is reached, the oldest
   * blocked bundle is unblocked. Blocked bundles will be skipped in future
   * sync operations.
   *
   * **Attention**: This option has no effect if `readyTimeout` is set to `0`.
   *
   * @since 0.1.0
   * @default false
   */
  autoBlockRolledBackBundles?: boolean;
  /**
   * Whether or not to automatically delete unused bundles.
   *
   * When enabled, the SDK will automatically delete unused bundles after
   * calling `ready()`. The current bundle, the next bundle and the last
   * bundle that successfully signaled readiness are never deleted.
   *
   * @since 0.1.0
   * @default false
   */
  autoDeleteBundles?: boolean;
  /**
   * The auto-update strategy for live updates.
   *
   * @since 0.1.0
   * @default 'none'
   * @example 'background'
   */
  autoUpdateStrategy?: AutoUpdateStrategy;
  /**
   * The directory where the SDK stores its bundles and state.
   *
   * @since 0.1.0
   * @default join(app.getPath('userData'), 'live-update')
   */
  dataDirectory?: string;
  /**
   * The default channel of the app.
   *
   * This can be overridden by `setChannel()` or the `channel` parameter
   * of `sync()`.
   *
   * @since 0.1.0
   * @example 'production'
   */
  defaultChannel?: string;
  /**
   * The absolute path to the directory containing the default bundle
   * (the web assets packaged with the app, containing an `index.html`).
   *
   * Required for `serve()`. In simple mode it is used as the fallback
   * result of `getCurrentBundlePath()` and as the reload target when
   * the default bundle is active.
   *
   * @since 0.1.0
   * @example join(__dirname, '..', 'renderer')
   */
  defaultBundlePath?: string;
  /**
   * The timeout in milliseconds for HTTP requests.
   *
   * @since 0.1.0
   * @default 60000
   */
  httpTimeout?: number;
  /**
   * A custom logger.
   *
   * @since 0.1.0
   * @default console
   */
  logger?: LiveUpdateLogger;
  /**
   * The public key to verify the integrity of the bundle.
   *
   * The public key must be a PEM-encoded RSA public key.
   *
   * @since 0.1.0
   */
  publicKey?: string;
  /**
   * The timeout in milliseconds to wait for the app to be ready
   * before rolling back to the previous bundle.
   *
   * It is strongly **recommended** to configure this option (e.g. `10000` ms)
   * so that the SDK can roll back in case of problems: if configured, the
   * app must call `ready()` within this timeout after every start or reload
   * of a live update bundle. This also enables the kill-safe boot rollback:
   * a marker is persisted before a new bundle loads and is only cleared by
   * `ready()`, so a crash or kill during boot is detected on the next start.
   *
   * Set to `0` to disable rollback protection.
   *
   * @since 0.1.0
   * @default 0
   * @example 10000
   */
  readyTimeout?: number;
  /**
   * The API domain of the [Capawesome Cloud](https://cloud.capawesome.io)
   * server **without** scheme or path.
   *
   * @since 0.1.0
   * @default 'api.cloud.capawesome.io'
   * @example 'api.cloud.capawesome.eu'
   */
  serverDomain?: string;
  /**
   * The version code of the app.
   *
   * @since 0.1.0
   * @default app.getVersion()
   */
  versionCode?: string;
  /**
   * The version name of the app.
   *
   * @since 0.1.0
   * @default app.getVersion()
   */
  versionName?: string;
}

/**
 * @since 0.1.0
 */
export interface ServeOptions {
  /**
   * The custom scheme under which the active bundle is served.
   *
   * The origin `<scheme>://bundle` stays stable across bundle
   * switches, so Web Storage, IndexedDB and service workers survive
   * updates.
   *
   * @since 0.1.0
   * @default 'live-update'
   */
  scheme?: string;
}

/**
 * The main process live update SDK.
 *
 * Mirrors the `@capawesome/capacitor-live-update` plugin API and adds
 * the Electron-specific serving integration.
 *
 * @since 0.1.0
 */
export interface LiveUpdate extends LiveUpdateApi {
  /**
   * Register a window with the SDK.
   *
   * Attached windows are reloaded by `reload()` (and by an automatic
   * rollback) and are allowed to call the SDK from the renderer via
   * the preload bridge.
   *
   * @since 0.1.0
   */
  attach(window: BrowserWindow): void;
  /**
   * Get the absolute path of the current bundle on disk (simple mode).
   *
   * Returns the configured `defaultBundlePath` when the default bundle
   * is active, or `null` if no `defaultBundlePath` is configured.
   * Load the returned directory's `index.html` into your window.
   *
   * @since 0.1.0
   */
  getCurrentBundlePath(): Promise<string | null>;
  /**
   * Get the URL under which the active bundle is served (serve mode).
   *
   * Only available after `serve()` has been called.
   *
   * @since 0.1.0
   * @example 'live-update://bundle/'
   */
  getServeUrl(): string;
  /**
   * Serve the active bundle over a privileged custom scheme
   * (recommended mode).
   *
   * Must be called BEFORE the app is ready, because privileged schemes
   * can only be registered before that point. Requires the
   * `defaultBundlePath` option so the built-in bundle can be served.
   *
   * The origin stays stable across bundle switches: localStorage,
   * IndexedDB and service workers survive updates.
   *
   * @since 0.1.0
   */
  serve(options?: ServeOptions): void;
}
